import { Level } from '../types';
import { COLOR_WHITE, COLOR_RED, COLOR_GREEN, COLOR_BLUE } from '../utils/colors';

export const LEVELS: Level[] = [
  {
    id: 'level1',
    name: '第一关：入门反射',
    description: '旋转镜子，把白光引导到接收器。点击镜子旋转。',
    rooms: [
      {
        id: 'room1',
        name: '房间 A',
        size: 400,
        position: { x: 0, y: 0 },
        rotation: 0,
        walls: [
          { exists: true },
          { exists: true },
          { exists: true },
          { exists: true },
        ],
        elements: [
          {
            id: 'src1',
            type: 'source',
            position: { x: 50, y: 200 },
            rotation: 0,
            color: { ...COLOR_WHITE },
            size: 24,
            rotatable: false,
          },
          {
            id: 'mirror1',
            type: 'mirror',
            position: { x: 300, y: 200 },
            rotation: 45,
            size: 40,
            rotatable: true,
          },
          {
            id: 'recv1',
            type: 'receiver',
            position: { x: 300, y: 50 },
            rotation: 1,
            color: { ...COLOR_WHITE },
            size: 28,
            rotatable: false,
          },
        ],
      },
    ],
  },
  {
    id: 'level2',
    name: '第二关：跨房间穿越',
    description: '光从A房间右边出去，会从B房间天花板进入。注意重力方向变了！',
    rooms: [
      {
        id: 'roomA',
        name: '房间 A',
        size: 350,
        position: { x: 0, y: 0 },
        rotation: 0,
        walls: [
          {
            exists: true,
            connection: {
              targetRoomId: 'roomB',
              targetWall: 3,
              rotation: 0,
              flip: false,
            },
          },
          { exists: true },
          { exists: true },
          { exists: true },
        ],
        elements: [
          {
            id: 'src2',
            type: 'source',
            position: { x: 50, y: 175 },
            rotation: 0,
            color: { ...COLOR_WHITE },
            size: 24,
            rotatable: false,
          },
          {
            id: 'mirror2a',
            type: 'mirror',
            position: { x: 175, y: 175 },
            rotation: 0,
            size: 40,
            rotatable: true,
          },
        ],
      },
      {
        id: 'roomB',
        name: '房间 B',
        size: 350,
        position: { x: 420, y: 0 },
        rotation: 0,
        walls: [
          { exists: true },
          { exists: true },
          { exists: true },
          {
            exists: true,
            connection: {
              targetRoomId: 'roomA',
              targetWall: 0,
              rotation: 0,
              flip: false,
            },
          },
        ],
        elements: [
          {
            id: 'mirror2b',
            type: 'mirror',
            position: { x: 175, y: 175 },
            rotation: 45,
            size: 40,
            rotatable: true,
          },
          {
            id: 'recv2',
            type: 'receiver',
            position: { x: 300, y: 175 },
            rotation: 2,
            color: { ...COLOR_WHITE },
            size: 28,
            rotatable: false,
          },
        ],
      },
    ],
  },
  {
    id: 'level3',
    name: '第三关：棱镜分光',
    description: '白光通过棱镜分成红绿蓝三色，分别导入对应颜色的接收器。',
    rooms: [
      {
        id: 'room3',
        name: '棱镜实验室',
        size: 450,
        position: { x: 0, y: 0 },
        rotation: 0,
        walls: [
          { exists: true },
          { exists: true },
          { exists: true },
          { exists: true },
        ],
        elements: [
          {
            id: 'src3',
            type: 'source',
            position: { x: 50, y: 225 },
            rotation: 0,
            color: { ...COLOR_WHITE },
            size: 24,
            rotatable: false,
          },
          {
            id: 'prism3',
            type: 'prism',
            position: { x: 225, y: 225 },
            rotation: 0,
            size: 50,
            rotatable: true,
          },
          {
            id: 'mirror3r',
            type: 'mirror',
            position: { x: 350, y: 100 },
            rotation: 135,
            size: 40,
            rotatable: true,
          },
          {
            id: 'mirror3b',
            type: 'mirror',
            position: { x: 350, y: 350 },
            rotation: 45,
            size: 40,
            rotatable: true,
          },
          {
            id: 'recvR',
            type: 'receiver',
            position: { x: 350, y: 50 },
            rotation: 1,
            color: { ...COLOR_RED },
            size: 28,
            rotatable: false,
          },
          {
            id: 'recvG',
            type: 'receiver',
            position: { x: 400, y: 225 },
            rotation: 2,
            color: { ...COLOR_GREEN },
            size: 28,
            rotatable: false,
          },
          {
            id: 'recvB',
            type: 'receiver',
            position: { x: 350, y: 400 },
            rotation: 3,
            color: { ...COLOR_BLUE },
            size: 28,
            rotatable: false,
          },
        ],
      },
    ],
  },
  {
    id: 'level4',
    name: '第四关：折叠迷宫',
    description: '三个房间折叠连接。光从A右出→B下入→B右出→C上入，把光送到C房间的接收器！',
    rooms: [
      {
        id: 'room4A',
        name: 'A (入口)',
        size: 300,
        position: { x: 0, y: 50 },
        rotation: 0,
        walls: [
          {
            exists: true,
            connection: {
              targetRoomId: 'room4B',
              targetWall: 1,
              rotation: 90,
              flip: false,
            },
          },
          { exists: true },
          { exists: true },
          { exists: true },
        ],
        elements: [
          {
            id: 'src4',
            type: 'source',
            position: { x: 40, y: 150 },
            rotation: 0,
            color: { ...COLOR_WHITE },
            size: 24,
            rotatable: false,
          },
        ],
      },
      {
        id: 'room4B',
        name: 'B (中转)',
        size: 300,
        position: { x: 370, y: 50 },
        rotation: 0,
        walls: [
          {
            exists: true,
            connection: {
              targetRoomId: 'room4C',
              targetWall: 3,
              rotation: 0,
              flip: false,
            },
          },
          {
            exists: true,
            connection: {
              targetRoomId: 'room4A',
              targetWall: 0,
              rotation: -90,
              flip: false,
            },
          },
          { exists: true },
          { exists: true },
        ],
        elements: [
          {
            id: 'mirror4b1',
            type: 'mirror',
            position: { x: 150, y: 150 },
            rotation: 45,
            size: 40,
            rotatable: true,
          },
        ],
      },
      {
        id: 'room4C',
        name: 'C (目标)',
        size: 300,
        position: { x: 740, y: 50 },
        rotation: 0,
        walls: [
          { exists: true },
          { exists: true },
          { exists: true },
          {
            exists: true,
            connection: {
              targetRoomId: 'room4B',
              targetWall: 0,
              rotation: 0,
              flip: false,
            },
          },
        ],
        elements: [
          {
            id: 'mirror4c1',
            type: 'mirror',
            position: { x: 150, y: 150 },
            rotation: 45,
            size: 40,
            rotatable: true,
          },
          {
            id: 'recv4',
            type: 'receiver',
            position: { x: 260, y: 150 },
            rotation: 2,
            color: { ...COLOR_WHITE },
            size: 28,
            rotatable: false,
          },
        ],
      },
    ],
  },
];
